name: Hello-action
on: 
  push:
    branches: 
      - main

jobs:
  my_hello:
    runs-on: [ubuntu-latest]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install requests module
        run: pip install requests

      - name: Run hello.py
        run: |
          echo "Run: Hello.py"
          python hello.py

#      - name: Git clone my repo
#        uses: actions/checkout@v1

#      - name: Run python script Hello.py
#        run : |
#          echo "Run: Hello.py"
#          hello.py          

#      - name: Git clone my repo
#        uses: actions/checkout@v1

