name: Hello-action
on: 
  push:
    branches: 
      - main

jobs:
  my_hello:
    runs-on: [ubuntu-latest]
    
    steps:
      - name: Run python script Hello.py
        run : |
          echo "Run: Hello.py"
          hello.py          

#      - name: Git clone my repo
#        uses: actions/checkout@v1
